import Head from "next/head";
import styles from "../styles/Home.module.css";
import BooksList from "../components/books/BooksList";
import Header from "../components/Header";
export default function Home({ books }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Allbooks" />

      <BooksList books={books} />
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(`http://localhost:3000/api/books`);
  const books = await response.json();
  return {
    props: {
      books,
    },
  };
}
